### ISSUE TITLE
大佬,我现在手里有一个罗技蓝牙触摸板,但是只能mac驱动,没windows驱动

### ISSUE THREAD

**Issue by CCluv** [imbushuo/mac-precision-touchpad#155]
这种没有现成上层驱动可分析hid设备想自己写个高精度触摸驱动有什么好思路吗,我是做网络驱动的,这个有点头大...不过我还有个windows版的触摸板(2.4G连接的),两个长的一样就是连接方式不一样,不知道windows版的驱动有没有参考价值

**Comment by imbushuo** [comment]
Assuming the trackpad use HID over Bluetooth, it is possible to retrieve HID report descriptor and decode the struct information. Other components including PTP sample report can be referred from my driver. You should look into the SPI driver since Bluetooth stack typically comes with a usable IO target for drivers' consumption.
