### ISSUE TITLE
[FEATURE REQUEST] Magic Mouse support

### ISSUE THREAD

**Issue by Rastafabisch** [imbushuo/mac-precision-touchpad#341]
[FEATURE REQUEST]

Hello! I really do enjoy using your driver on my MacBook Pro (15”, 2017). It’s basically working flawlessly!

On your To-Do list I’ve seen planned support for the Magic Trackpad 2 [via bluetooth](https://github.com/imbushuo/mac-precision-touchpad/issues/229).
Once this functionality is implemented would it be possible for you to add Magic Mouse support as well? While the touch gestures are limited of course, Mac-like functionality would still be useful. Two finger double tab for “Mission Control” (open windows overview) and of course swipe navigation (forward/backward) for supported browsers and the explorer comes to mind.

<img width="780" alt="mouse_gestures" src="https://user-images.githubusercontent.com/38974866/92175969-dc05ba00-ee3d-11ea-80a9-6fadef9559ac.png">

Best,
Rastafabisch

**Comment by GoldenChaos** [comment]
I just want to throw my hat in this ring because I am currently trying to use a Magic Mouse 2 with an old Surface Pro 2 (for fun) and it is an absolute nightmare. The only precision drivers that are available are Magic Utilities, which is not only not free but charges on a subscription-per-device basis, which has to be one of the most insane business models I've ever seen from a software company.

Is there any chance of a Magic Mouse variant of this driver? I'd lose my mind (in a good way).

**Comment by imbushuo** [comment]
It will be too tricky to support Magic Mouse due to the way it works (as well as its report descriptor), and I don't believe you will get a good experience with it.
