### ISSUE TITLE
Error installing on windows 10

### ISSUE THREAD

**Issue by Coon1123** [imbushuo/mac-precision-touchpad#342]
**Describe the bug**
When i plug the MT2 via USB cable, the system recognizes a "HID-Compliant Mouse". Then, when I try installing the driver on the Device Manager, I get the error "...make sure it is designed to work with windows for x64-based systems". I am trying to install AmtPtpDevice.inf that I decompressed from Drivers-amd64-ReleaseMSSigned, release 3826.

**To Reproduce**
See above. 

**Expected behavior**
I expected the driver to install, windows to recognize the MT2 as a trackpad and give it funcionality as it does its synaptics trackpad. Right now i can only move the cursor and click, cant use more than 1 finger on it.

**Traces**
Dont know what WPP tracers are...

**Environment**
Lenovo Thinkpad T450, with windows 10 enterprise, version 1809, built 17763.1339
![print1](https://user-images.githubusercontent.com/70725796/92180763-3a22a500-ee1e-11ea-8f15-3ac461ec3ba5.png)

**Comment by Bananaman** [comment]
Install chocolatey: https://chocolatey.org/

Then open a powershell admin prompt and type: `choco install mac-precision-touchpad` (it installs this package: https://chocolatey.org/packages/mac-precision-touchpad/)

That's all. To update in the future you go to a powershell admin prompt and type `choco upgrade all`

**Comment by niklase2** [comment]
I hope I'm not too late, but you probably downloaded the wrong version for your computer. When you choose which version you want to download, there are 2 options: **arm64 and amd64**. In videos or instructions you are going to see the amd64 one, because it is the right choice for most people, but maybe you have to choose the other one (arm64). Also make sure that you first unzip it and **RIGHT CLICK THE 2ND FILE** in the folder and install.
Has this solved your issue?

**Comment by imbushuo** [comment]
Closed since this is a stale ticket.
