### ISSUE TITLE
Three Finger Drag

### ISSUE THREAD

**Issue by oscarat50** [imbushuo/mac-precision-touchpad#415]
**Pre-report checks**
- [x] Have you checked (use search) [Azure DevOps Board]
Yes, I did. Found no request similar to mine. 

**Is your feature request related to a problem? Please describe.**
I just use three finger drag a lot, I miss that feature, it's essential to my workflow.

**Describe the solution you'd like**
Implementation of the three finger drag feature.

**Describe alternatives you've considered**
None

**Additional context**
Thanks a lot for your hard work!

[AB#727](https://ligstd.visualstudio.com/7694e0d0-94e3-4fd2-b39a-ecd261e1ba2e/_workitems/edit/727)

**Comment by MagicUtilities** [comment]
It's unlikely that the 3 finger drag feature comes to this driver because of the very nature this driver works. It only converts the raw trackpad touches so the Windows HID class driver can understand them.

It does NOT interpret the touches. As the 3 finger dragging is not part of Windows gestures, this driver would need to modify the touches on the way up (3 finger touch into 1 finger click and hold) to achieve your feature request.

See also #84 

You might consider the [Magic Utilities](https://magicutilities.net/magic-trackpad/features) which supports 3 finger dragging.

**Comment by abulka** [comment]
> You might consider the Magic Utilities which supports 3 finger dragging.

Does that paid product supplant or replace this wonderful free `mac-precision-touchpad` driver?

P.S. The three finger drag to move windows and select text is so ingrained in me from using my Mac, I miss it under Windows.

**Comment by MagicUtilities** [comment]
Unfortunately by their very nature, both drivers can't coexist together so the Magic Utilities replaces this driver.

Three finger dragging is not part of the Magic Trackpad. It is only done by interpreting the raw touches by a built-in software driver on macOS. The Magic Utilities do the same on Windows.
