### ISSUE TITLE
Release 3979 - Rightclick/Multitouch/Gestures not working on Bluetooth

### ISSUE THREAD

**Issue by GilbertChan** [imbushuo/mac-precision-touchpad#420]
Other than mouse moving, I am unable to right click, use multitouch and gestures when connected through Bluetooth.

Occurs when I installed Release 3979 and paired with Bluetooth on Windows 10 21H1

I'm not sure if this is expected behavior as the features have not been implemented yet or there is something wrong with my setup. These features are available when I am connected via USB on the same release.

[AB#736](https://ligstd.visualstudio.com/7694e0d0-94e3-4fd2-b39a-ecd261e1ba2e/_workitems/edit/736)

**Comment by lloydo3000** [comment]
Works for me on Bluetooth

From: Gilbert ***@***.***>
Sent: Saturday, 24 July 2021 9:05
To: ***@***.***>
Cc: ***@***.***>
Subject: [imbushuo/mac-precision-touchpad] Release 3979 - Rightclick/Multitouch/Gestures not working on Bluetooth (#420)


Other than mouse moving, I am unable to right click, use multitouch and gestures when connected through Bluetooth.

Occurs when I installed Release 3979 and paired with Bluetooth on Windows 10 21H1

I'm not sure if this is expected behavior as the features have not been implemented yet or there is something wrong with my setup. These features are available when I am connected via USB on the same release.

**Comment by GilbertChan** [comment]
This is what I see in my Device Manager when connected via bluetooth with the latest release installed. 
![image](https://user-images.githubusercontent.com/6663661/126871418-c220da04-7cac-4074-98aa-e11ee8deb297.png)

This is what I see when connected with USB.
![image](https://user-images.githubusercontent.com/6663661/126871472-2b12909d-1235-4b54-9046-4269acc1034f.png)

**Comment by GilbertChan** [comment]
I found the issue, I had to uninstall the Apple Bluetooth compatibility drivers. It is now working and running with the Release 3979 drivers.

**Comment by peter-tudosa** [comment]
Hey @GilbertChan I have the same issue, where did you find the Apple Bluetooth compatibility drivers?

**Comment by GilbertChan** [comment]
@razvan-tudosa If I remember correctly, I uninstalled the Apple Bluetooth compatibility drivers in Device Manager under Human Interface Devices.

**Comment by peter-tudosa** [comment]
I see, well I did not have them in there, but I saw that I can install the drivers from the terminal as well using _chocolatey_ and after that everything worked out fine. I think the drivers were not installed fine with the traditional way for some reason.

Thanks for answering anyway!
