### ISSUE TITLE
Driver for Linux

### ISSUE THREAD

**Issue by AdityaGarg8** [imbushuo/mac-precision-touchpad#422]
Could you please provide driver for Linux too. A team has got linux running on T2 Macs on <wiki.t2linux.org>.

**Comment by imbushuo** [comment]
It's already in mainline iirc.

**Comment by matyhattam** [comment]
Hello, 
Any news regarding the linux version of this incredible project ? :)

**Comment by benwiley4000** [comment]
Hi I wanted to +1 this request if there's any remote chance you would be interested in working on it. The magic trackpad is supported by the older Synaptics input driver, but modern Linux distributions have moved away from Synaptics and it's largely incompatible with modern libinput stuff.

I briefly installed Synaptics, but it caused too many problems, so I switched back and I simply stopped using the magic trackpad with Linux, which has required me to change my workspace layout.

The main issue with use under libinput is that you're required to hold down the left click in order to move the mouse - otherwise it doesn't move at all.

Of course this is a bit out of scope of the Windows implementation, but you might be well-positioned to provide some insight into how to make the magic trackpad work with modern Linux distributions. Note that I'm not using Wayland, although some are moving toward this.

**Comment by AdityaGarg8** [comment]
For T2 Macs we have been successful in patching hid-magicmouse

**Comment by AdityaGarg8** [comment]
As far as gestures are considered, you need to configure libinput, which is a userspace thing.

**Comment by AdityaGarg8** [comment]
5 years ago I was a noob when I opened this PR lol.
